Repository chirag3003/project-maple, pull requests merged in 2022-10, with the labels that each got.

#4 completed basic layout
  src/packages/frontend/.eslintrc.json
  src/packages/frontend/components/Seo/index.jsx
  src/packages/frontend/components/layouts/MainLayout/MainLayout.style.jsx
  src/packages/frontend/components/layouts/MainLayout/Profile.jsx
  src/packages/frontend/components/layouts/MainLayout/Sidebar.jsx
  src/packages/frontend/components/layouts/MainLayout/Sidebar.style.jsx
  src/packages/frontend/components/layouts/MainLayout/index.jsx
  src/packages/frontend/package.json
  src/packages/frontend/pages/index.js
  src/packages/frontend/public/logo.svg
  src/packages/frontend/styles/globals.css
Labels: hacktoberfest

#6 Feature/backend setup
  .eslintrc.js
  .husky/pre-commit
  jsconfig.json
  package.json
  src/packages/backend/.gitignore
  src/packages/backend/package.json
  src/packages/backend/src/controllers/auth.controller.ts
  src/packages/backend/src/helpers/checkENV.ts
  src/packages/backend/src/helpers/errors.ts
  src/packages/backend/src/helpers/index.ts
  src/packages/backend/src/helpers/middlewares.ts
  src/packages/backend/src/helpers/types.d.ts
  src/packages/backend/src/helpers/utilities.ts
  src/packages/backend/src/index.ts
  src/packages/backend/src/interfaces/auth.interface.ts
  src/packages/backend/src/libs/auth.adapter.ts
  src/packages/backend/src/libs/auth.service.ts
  src/packages/backend/src/routes/auth.routes.ts
  src/packages/backend/src/routes/index.ts
  src/packages/backend/src/types/index.d.ts
  src/packages/backend/src/validations/auth.validation.ts
  src/packages/backend/src/validations/utils.ts
  src/packages/backend/tsconfig.json
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted

#22 Added Auth Module
  package.json
  src/packages/backend/package.json
  src/packages/backend/src/controllers/auth.controller.ts
  src/packages/backend/src/helpers/index.ts
  src/packages/backend/src/helpers/mongodb.ts
  src/packages/backend/src/index.ts
  src/packages/backend/src/interfaces/auth.interface.ts
  src/packages/backend/src/interfaces/user.interface.ts
  src/packages/backend/src/libs/auth.service.ts
  src/packages/backend/src/models/auth.ts
  src/packages/backend/src/models/todo.ts
  src/packages/backend/src/routes/auth.routes.ts
  src/packages/backend/src/services/user.service.ts
  src/packages/backend/src/validations/auth.validation.ts
  src/packages/backend/src/validations/utils.ts
  src/packages/frontend/package.json
  src/packages/frontend/pages/_app.js
  src/packages/frontend/pages/index.js
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted

#44 Feature/todo api
  .idea/.gitignore
  .idea/discord.xml
  .idea/modules.xml
  .idea/project-maple.iml
  .idea/vcs.xml
  src/packages/backend/src/controllers/todo.controller.ts
  src/packages/backend/src/helpers/utilities.ts
  src/packages/backend/src/interfaces/auth.interface.ts
  src/packages/backend/src/interfaces/todo.interface.ts
  src/packages/backend/src/libs/auth.service.ts
  src/packages/backend/src/models/auth.model.ts
  src/packages/backend/src/models/todo.model.ts
  src/packages/backend/src/models/todo.ts
  src/packages/backend/src/routes/todo.routes.ts
  src/packages/backend/src/services/todo.service.ts
  src/packages/backend/src/services/user.service.ts
  src/packages/backend/src/validations/todo.validation.ts
  src/packages/backend/src/validations/utils.ts
Labels: hacktoberfest, hacktoberfest-accepted

#46 Gk ram dev/root layout
  src/packages/frontend/components/Dashboard/Dashboard.style.jsx
  src/packages/frontend/components/Files/Files.style.jsx
  src/packages/frontend/components/Files/index.jsx
  src/packages/frontend/components/common/Breakpoints/BreakPoints.index.jsx
  src/packages/frontend/components/common/Logo/Logo.index.jsx
  src/packages/frontend/components/common/ProfileImage/ProfileImage.index.jsx
  src/packages/frontend/components/layouts/MainLayout/MainLayout.style.jsx
  src/packages/frontend/components/layouts/MainLayout/Profile.jsx
  src/packages/frontend/components/layouts/MainLayout/Profile.style.jsx
  src/packages/frontend/components/layouts/MainLayout/Sidebar.jsx
  src/packages/frontend/components/layouts/MainLayout/Sidebar.style.jsx
  src/packages/frontend/components/layouts/MainLayout/index.jsx
  src/packages/frontend/components/layouts/RootLayout/Body/Body.index.jsx
  src/packages/frontend/components/layouts/RootLayout/Body/Header/Header.index.jsx
  src/packages/frontend/components/layouts/RootLayout/Body/Sidebar/Sidebar.index.jsx
  src/packages/frontend/components/layouts/RootLayout/Body/Sidebar/Sidebar.styles.jsx
  src/packages/frontend/components/layouts/RootLayout/RootLayout.index.jsx
  src/packages/frontend/components/layouts/RootLayout/RootLayout.styles.jsx
  src/packages/frontend/components/layouts/RootLayout/Sidebar/Sidebar.index.jsx
  src/packages/frontend/components/layouts/RootLayout/Sidebar/Sidebar.styles.jsx
  src/packages/frontend/components/layouts/RootLayout/index.jsx
  src/packages/frontend/jsconfig.json
  src/packages/frontend/package.json
  src/packages/frontend/pages/_app.js
  src/packages/frontend/pages/_app.jsx
  src/packages/frontend/pages/create.jsx
  src/packages/frontend/pages/create/index.jsx
  src/packages/frontend/pages/index.js
  src/packages/frontend/pages/index.jsx
  src/packages/frontend/pages/logs.jsx
  src/packages/frontend/pages/pastebin.js
  src/packages/frontend/pages/pastebin/index.jsx
  src/packages/frontend/pages/services.jsx
  src/packages/frontend/pages/services/index.jsx
  src/packages/frontend/pages/store.jsx
  src/packages/frontend/pages/store/index.jsx
  src/packages/frontend/public/logo.svg
  yarn.lock
Labels: enhancement, hacktoberfest
